"""add weekly muscle group volume and citations

Revision ID: 0347b47fcb78
Revises: 250625008295
Create Date: 2026-10-02 15:54:38.840024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0347b47fcb78'
down_revision: Union[str, Sequence[str], None] = '250625008295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('weekly_sets', sa.Integer(), nullable=False),
    sa.Column('grounding_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volume_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['muscle_group_volumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_citations')
    op.drop_table('muscle_group_volumes')
    # ### end Alembic commands ###
