"""add rule justifications and citations

Revision ID: 04c33db6e679
Revises: ace27f8e8300
Create Date: 2026-10-03 21:48:32.748899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c33db6e679'
down_revision: Union[str, Sequence[str], None] = 'ace27f8e8300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_justifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('grounding_note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_table('rule_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rule_justifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_citations')
    op.drop_table('rule_justifications')
    # ### end Alembic commands ###
