"""add secondary muscle groups to exercise slots

Revision ID: 250625008295
Revises: 805f590eea35
Create Date: 2026-10-02 15:39:01.515417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250625008295'
down_revision: Union[str, Sequence[str], None] = '805f590eea35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_slots', sa.Column('secondary_muscle_groups', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_slots', 'secondary_muscle_groups')
    # ### end Alembic commands ###
