"""add rir and per-field notes for reps and rir

Revision ID: 289a4ec0fd86
Revises: 0347b47fcb78
Create Date: 2026-10-02 16:30:52.933351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289a4ec0fd86'
down_revision: Union[str, Sequence[str], None] = '0347b47fcb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_prescriptions', sa.Column('rir', sa.String(), server_default='', nullable=False))
    op.add_column('weekly_prescriptions', sa.Column('reps_grounding_note', sa.String(), nullable=True))
    op.add_column('weekly_prescriptions', sa.Column('rir_grounding_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_prescriptions', 'rir_grounding_note')
    op.drop_column('weekly_prescriptions', 'reps_grounding_note')
    op.drop_column('weekly_prescriptions', 'rir')
    # ### end Alembic commands ###
