"""add muscle_group_frequencies and frequency_citations tables

Revision ID: 431e16986825
Revises: 8d24ebf4e2ce
Create Date: 2026-08-19 22:21:48.205212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431e16986825'
down_revision: Union[str, Sequence[str], None] = '8d24ebf4e2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('grounding_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frequency_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['frequency_id'], ['muscle_group_frequencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequency_citations')
    op.drop_table('muscle_group_frequencies')
    # ### end Alembic commands ###
