"""add muscle_group to exercise_slots

Revision ID: 433e050876f5
Revises: 10e3e6793cbe
Create Date: 2026-07-31 20:53:06.730050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433e050876f5'
down_revision: Union[str, Sequence[str], None] = '10e3e6793cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_slots', sa.Column('muscle_group', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_slots', 'muscle_group')
    # ### end Alembic commands ###
