"""add shared answers and exercise is_compound

Revision ID: 5e6dd9edf3a5
Revises: 04c33db6e679
Create Date: 2026-10-04 02:20:26.586628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6dd9edf3a5'
down_revision: Union[str, Sequence[str], None] = '04c33db6e679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('shared_answer_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['shared_answers.id'], ),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exercise_slots', sa.Column('is_compound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_slots', 'is_compound')
    op.drop_table('shared_answer_citations')
    op.drop_table('shared_answers')
    # ### end Alembic commands ###
