"""add grounding_note to weekly_prescriptions

Revision ID: 8d24ebf4e2ce
Revises: 9d2672fae730
Create Date: 2026-08-19 16:49:32.089272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d24ebf4e2ce'
down_revision: Union[str, Sequence[str], None] = '9d2672fae730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_prescriptions', sa.Column('grounding_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_prescriptions', 'grounding_note')
    # ### end Alembic commands ###
