"""add citations and prescription_citations tables

Revision ID: 9d2672fae730
Revises: 433e050876f5
Create Date: 2026-08-02 19:46:19.642984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2672fae730'
down_revision: Union[str, Sequence[str], None] = '433e050876f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('snippet', sa.String(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['weekly_prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
