"""add volume preference to programs

Revision ID: ace27f8e8300
Revises: 289a4ec0fd86
Create Date: 2026-10-02 17:08:01.906610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace27f8e8300'
down_revision: Union[str, Sequence[str], None] = '289a4ec0fd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('volume_preference', sa.String(), server_default='moderate', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'volume_preference')
    # ### end Alembic commands ###
