"""create initial six tables

Revision ID: c30a81a41f97
Revises: 
Create Date: 2026-07-19 23:30:43.831482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30a81a41f97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_week', sa.Integer(), nullable=False),
    sa.Column('end_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesocycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('rest_days_before', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mesocycle_id'], ['mesocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_template_id'], ['day_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_slot_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('load', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_slot_id'], ['exercise_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_prescriptions')
    op.drop_table('exercise_slots')
    op.drop_table('day_templates')
    op.drop_table('mesocycles')
    op.drop_table('programs')
    op.drop_table('users')
    # ### end Alembic commands ###
